lucky_numbers = [4,8,15,16,23,42]
friends = ["Kevin", "Karen", "Jim", "Oscar", "Mike", "Jim"]
friends.sort()
lucky_numbers.sort()
lucky_numbers.reverse()
print(lucky_numbers)
friends2=friends.copy()
print(friends2)
friends.extend(lucky_numbers)
friends.insert(1, "Kelly")
print(friends.count("Jim"))
friends.remove("Jim")
print(friends)
friends.pop()
print(friends)
print(friends.index("Kevin"))
friends.clear()
print(friends)